package streaming.structured

import org.apache.log4j.{Level, Logger}
import org.apache.spark.{HashPartitioner, SparkConf}
import org.apache.spark.streaming.{Seconds, StreamingContext}


object StatefulNetworkWordCount {
  def main(args: Array[String]) {
    if (args.length < 2) {
      System.err.println("Usage: StatefulNetworkWordCount <hostname> <port>")
      //System.exit(1)
    }

    Logger.getLogger("org.apache.spark").setLevel(Level.WARN)

    val updateFunc = (values: Seq[Int], state: Option[Int]) => {
      val currentCount = values.sum
      val previousCount = state.getOrElse(0)
      Some(currentCount + previousCount)
    }

    val newUpdateFunc = (iterator: Iterator[(String, Seq[Int], Option[Int])]) => {
      iterator.flatMap(t => updateFunc(t._2, t._3).map(s => (t._1, s)))
    }

    val sparkConf = new SparkConf().setAppName("StatefulNetworkWordCount").setMaster("local")
    // Create the context with a 1 second batch size
    val ssc = new StreamingContext(sparkConf, Seconds(1))
    ssc.checkpoint("/tmp/test")

    // Initial RDD input to updateStateByKey
    val initialRDD = ssc.sparkContext.parallelize(List(("hello", 1), ("world", 1)))

    // Create a ReceiverInputDStream on target ip:port and count the
    // words in input stream of \n delimited test (eg. generated by 'nc')
    val lines = ssc.socketTextStream("localhost", 3000)
    //lines.foreachRDD(x=> x.foreach(s=>println(s._1)))
    val words = lines.flatMap(_.split("\t"))
    //println(lines+": "+words)
    words.foreachRDD(x=>x.foreach(println))
    val wordDstream = words.map(x => (x, 1))
    //wordDstream.foreachRDD(x=>x.foreach(println))
    // Update the cumulative count using updateStateByKey
    // This will give a Dstream made of state (which is the cumulative count of the words)
//    val stateDstream = wordDstream.updateStateByKey[Int](newUpdateFunc,
//      new HashPartitioner (ssc.sparkContext.defaultParallelism), true, initialRDD)
//    wordDstream.updateStateByKey[Int](newUpdateFunc,
//      new HashPartitioner (ssc.sparkContext.defaultParallelism), true, initialRDD).print()
//    stateDstream.print()
    ssc.start()
    ssc.awaitTermination()
  }
}
